### ISSUE TITLE
Implementation classes cannot be generated in signed packages

### ISSUE THREAD

**Issue by raner** [raner/projo#144]
It is not possible to add generated implementation classes to signed packages (such as OSGi bundles).

For example, Projo can be used to create concrete annotation objects (given an annotation class) in the following fashion (Xtend syntax):
```
  def <_Type_ extends java.lang.annotation.Annotation> _Type_ annotation(Class<_Type_> annotation)
  {
    Projo.creates(annotation).with[annotationType].create(annotation)
  }
```
When this is used in an OSGi context to create, for example, a `javax.inject.Inject` object, this will result in the following exception:
```
java.lang.IllegalStateException: java.lang.SecurityException: class "javax.inject.Inject$Projo"'s signer information does not match signer information of other classes in the same package
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$UsingUnsafeInjection.defineClass(ClassInjector.java:1031)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:279)
	at net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:114)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:233)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:144)
	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:100)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6154)
	at pro.projo.internal.rcg.RuntimeCodeGenerationHandler.generateImplementation(RuntimeCodeGenerationHandler.java:154)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at pro.projo.internal.rcg.RuntimeCodeGenerationHandler.getImplementationOf(RuntimeCodeGenerationHandler.java:127)
	at pro.projo.internal.rcg.RuntimeCodeGenerationProjo$1$1.returnInstance(RuntimeCodeGenerationProjo.java:80)
	at pro.projo.internal.rcg.RuntimeCodeGenerationProjo$1$1.with(RuntimeCodeGenerationProjo.java:113)
	at pro.projo.singles.Intermediate.lambda$with$0(Intermediate.java:47)
...
Caused by: java.lang.SecurityException: class "javax.inject.Inject$Projo"'s signer information does not match signer information of other classes in the same package
	at java.base/java.lang.ClassLoader.checkCerts(ClassLoader.java:1151)
	at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:906)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1015)
	at java.base/java.lang.ClassLoader$ByteBuddyAccessor$kEb7Tcxa.defineClass(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$UsingUnsafeInjection.defineClass(ClassInjector.java:1027)
	... 41 more
```
Alternatively, there is also a slightly different failure mode:
```
java.lang.IllegalStateException: java.lang.NoClassDefFoundError: pro/projo/internal/ProjoObject
	at fxxx.generator.tests.TranslationUtilitiesTest.testAnnotation(TranslationUtilitiesTest.java:34)
Caused by: java.lang.ClassNotFoundException: pro.projo.internal.ProjoObject cannot be found by javax.inject_1.0.0.v20091030
	at fxxx.generator.tests.TranslationUtilitiesTest.testAnnotation(TranslationUtilitiesTest.java:34)
```
Specifically, the former was observed when running JUnit tests in Eclipse, and the latter occurred during a Maven build using the `org.eclipse.tycho:tycho-surefire-plugin` for unit test execution. The root causes are slightly different (not being able to add a class to a signed package, versus not being able to access a Projo runtime class from outside the package), but a possible solution to address both scenarios is to create the implementation class in the default package instead.

Detecting this situation before it occurs can probably be achieved by inspecting the target class's `ProtectionDomain`, though it might not be that simple in practice. Alternatively, though much less preferably, it might be possible to detect it _after the fact_, i.e. by catching the exception and starting over the entire generation process, this time using the default package. Lastly, the problem could be solved in a manual fashion, i.e. by allowing client code to pass a flag indicating that the implementation class should be generated in the default package.

**Comment by raner** [comment]
Providing a manual way to create implementations in the default package fixed the first problem ("_signer information does not match signer information of other classes in the same package_"), but the second problem ("_NoClassDefFoundError: pro/projo/internal/ProjoObject_") still remains.
It is possible that this could be related to `pro.projo.internal` and `pro.projo.internal.proxy` being declared as internal packages (not exported), or it could have to with how the Projo library is used when the problem occurs (notably, this problem - or a very similar one - also occurs in code that is executed in a Maven plug-in, outside of an OSGi context).

Closing this ticket for now; automatic detection can be done later in a separate ticket.
