### ISSUE TITLE
Provide a debug option for generated code

### ISSUE THREAD

**Issue by raner** [raner/projo#191]
Occasionally, there are problems with the runtime-generated bytecode that Projo produces, for example, one might see an error message like this:
```
java.util.ServiceConfigurationError: bootstrap.Bootstrap: Provider natives.bootstrap.Bootstrap could not be instantiated
	at natives.IntegerTest.installBootstrap(IntegerTest.java:19)
Caused by: com.google.inject.CreationException: 
Unable to create injector, see the following errors:

1) [Guice/ErrorInjectingConstructor]: IncompatibleClassChangeError: Interface method reference: 'Id Something.id()', is in an indirect superinterface of False$Projo
  at False$Projo.<init>(Unknown Source)
  while locating False$Projo
  at Bootstrap$1.configure(Bootstrap.java:69)
  at Provider.booleanFalse(Provider.java:30)
      \_ for field booleanFalse
  at Bootstrap._addBinding(Bootstrap.java:122)
```
This vaguely suggests that there is something wrong with the implementation of the constructor for `False$Projo`, but the exact nature of the problem is hard to diagnose because there is no "source code" per se, and no `.class` file either. The generated bytecode only exists within the JVM.

It would be nice if there were a way to easily get hold of the class file for a generated type (e.g., by saving a copy in `/tmp` or some other specified location).

**Comment by raner** [comment]
_For future reference:_ the debug property is called **`pro.projo.debug.path`** and must specify an absolute path to a folder where generated class files will be stored (e.g., `/tmp`).

From a Maven build for Projo itself this feature can be enabled by this command-line argument:

 &nbsp; &nbsp; `mvn clean install` **`-DargLine="-Dpro.projo.debug.path=/tmp"`**

This will result in debug classes to be saved, e.g., during test execution.

In a build for a downstream project, the command-line syntax is the usual:

 &nbsp; &nbsp; `mvn clean install` **`-Dpro.projo.debug.path=/tmp`**
