### ISSUE TITLE
Cached mechanism invokes cached method on incorrect type

### ISSUE THREAD

**Issue by raner** [raner/projo#192]
In a downstream project, this exception is thrown when initializing a Projo-created object that has an inherited (!) `@Cached` method:
```
[Guice/ErrorInjectingConstructor]: IncompatibleClassChangeError: Interface method reference: 'Id Something.id()', is in an indirect superinterface of Booleans$Projo
  at Booleans$Projo.<init>(Unknown Source)
  while locating Booleans$Projo
  at natives.bootstrap.Bootstrap$1.lambda$configure$2(Bootstrap.java:59)
  while locating Booleans

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
Caused by: IncompatibleClassChangeError: Interface method reference: 'Id Something.id()', is in an indirect superinterface of Booleans$Projo
	at Booleans$Projo.<init>(Unknown Source)
	at Booleans$Projo$$FastClassByGuice$$2016561.GUICE$TRAMPOLINE(<generated>)
	at Booleans$Projo$$FastClassByGuice$$2016561.apply(<generated>)
	at DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
	at ConstructorInjector.provision(ConstructorInjector.java:114)
	at ConstructorInjector.construct(ConstructorInjector.java:91)
	at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at FactoryProxy.get(FactoryProxy.java:60)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
	at InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
	at InternalInjectorCreator.build(InternalInjectorCreator.java:113)
	at Guice.createInjector(Guice.java:87)
	at Guice.createInjector(Guice.java:69)
	at Guice.createInjector(Guice.java:59)
	at natives.bootstrap.Bootstrap.<init>(Bootstrap.java:74)
	at java.base/NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/Constructor.newInstance(Constructor.java:481)
	at java.base/ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:782)
	at java.base/ServiceLoader$ProviderImpl.get(ServiceLoader.java:724)
	at java.base/ServiceLoader$3.next(ServiceLoader.java:1396)
	at java.base/ServiceLoader.findFirst(ServiceLoader.java:1811)
	at bootstrap.Bootstrap.load(Bootstrap.java:34)
	at Utilities.optional(Utilities.java:92)
	at Optionals.<clinit>(Optionals.java:21)
	at java.base/NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/Constructor.newInstance(Constructor.java:481)
	at natives.bootstrap.Bootstrap$1.lambda$configure$1(Bootstrap.java:44)
	at java.base/ArrayList.forEach(ArrayList.java:1510)
	at natives.bootstrap.Bootstrap$1.configure(Bootstrap.java:53)
	at AbstractModule.configure(AbstractModule.java:66)
	at Elements$RecordingBinder.install(Elements.java:409)
	at Elements.getElements(Elements.java:108)
	at InjectorShell$Builder.build(InjectorShell.java:160)
	at InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at Guice.createInjector(Guice.java:87)
	at Guice.createInjector(Guice.java:69)
	at Guice.createInjector(Guice.java:59)
	at natives.bootstrap.Bootstrap.<init>(Bootstrap.java:74)
	at IntegerTest.installBootstrap(IntegerTest.java:19)
```

**Comment by raner** [comment]
The problematic bytecode in question is:
```
  public fxxx.lang.System$Projo();
    descriptor: ()V
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=4, locals=1, args_size=1
         0: aload_0
         1: dup
         2: invokespecial #33                 // Method pro/projo/internal/rcg/runtime/DefaultToStringObject."<init>":()V
         5: pop
         6: aload_0
         7: iconst_1
         8: ldc           #38                 // MethodHandle REF_invokeSpecial fxxx/lang/Something.id:()Lfxxx/lang/Id;
        10: aload_0
        11: invokestatic  #42                 // Method pro/projo/internal/rcg/runtime/Cache.create:(ILjava/lang/invoke/MethodHandle;Ljava/lang/Object;)Lpro/projo/internal/rcg/runtime/Cache;
        14: putfield      #16                 // Field id:Lpro/projo/internal/rcg/runtime/Cache;
        17: return
```

**Comment by raner** [comment]
When running on Zulu VM there are some additional stack traces:
```
java.lang.RuntimeException: no such method: pro.projo.CacheTest$Something.id()Id/invokeSpecial
	at pro.projo.internal.rcg.RuntimeCodeGenerationProjo$1$1.returnInstance(RuntimeCodeGenerationProjo.java:96)
	at pro.projo.Projo.create(Projo.java:194)
	at pro.projo.CacheTest.testInheritedCachedMethod(CacheTest.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        ...
Caused by: java.lang.IllegalAccessError: no such method: pro.projo.CacheTest$Something.id()Id/invokeSpecial
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:483)
	at pro.projo.CacheTest$Value$Projo.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at pro.projo.internal.rcg.RuntimeCodeGenerationProjo$1$1.returnInstance(RuntimeCodeGenerationProjo.java:82)
	... 43 more
Caused by: java.lang.IncompatibleClassChangeError: Interface method reference: pro.projo.CacheTest$Something.id()Lpro/projo/CacheTest$Id;, is in an indirect superinterface of pro.projo.CacheTest$Value$Projo
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394)
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750)
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477)
	... 49 more
```

**Comment by raner** [comment]
It appears that `invokespecial` can really only invoke methods from the direct supertype, and the [documentation](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-6.html#jvms-6.5.invokespecial) states as much ("_...special handling for superclass, private, and instance initialization method invocations_" - though it doesn't specifically say _direct superclass_...).

For the test case (`CacheTest.testInheritedCachedMethod`), the scenario presents itself as follows:
```
    ┌─────────────┐
    │  Something  │
    │ «interface» │
    ├─────────────┤
    │ id()        │
    └─────────────┘
           Δ
           │
    ┌─────────────┐
    │    Value    │
    │ «interface» │
    └─────────────┘
           Δ
           ┊
    ┌─────────────┐
    │ Value$Projo │
    ├─────────────┤
    │ id()        │
    └─────────────┘
```
The generated code in `Value$Projo` invokes `Something.id()` using `invokespecial`, but the direct supertype is `Value`, not `Something`. Possibly the problem could be rectified by simply always using the direct supertype (`Value` in this case) for constructing the `REF_invokeSpecial` method handle?
The question is what would happen if `Value` provided an overriding implementation of `id()`: unless that implementation also has an `@Cached` annotation, no overriding implementation should be provided in `Value$Projo` at all.
